In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./Lipstick.csv')

In [3]:
df

Id    Age  Income  Gender       Ms Buys
0    1    <21    High    Male   Single   No
1    2    <21    High    Male  Married   No
2    3  21-35    High    Male   Single  Yes
3    4    >35  Medium    Male   Single  Yes
4    5    >35     Low  Female   Single  Yes
5    6    >35     Low  Female  Married   No
6    7  21-35     Low  Female  Married  Yes
7    8    <21  Medium    Male   Single   No
8    9    <21     Low  Female  Married  Yes
9   10    >35  Medium  Female   Single  Yes
10  11    <21  Medium  Female  Married  Yes
11  12  21-35  Medium    Male  Married  Yes
12  13  21-35    High  Female   Single  Yes
13  14    >35  Medium    Male  Married   No

In [7]:
df.drop(['Id'],axis=1, inplace =True)


In [8]:
df

Age  Income  Gender       Ms Buys
0     <21    High    Male   Single   No
1     <21    High    Male  Married   No
2   21-35    High    Male   Single  Yes
3     >35  Medium    Male   Single  Yes
4     >35     Low  Female   Single  Yes
5     >35     Low  Female  Married   No
6   21-35     Low  Female  Married  Yes
7     <21  Medium    Male   Single   No
8     <21     Low  Female  Married  Yes
9     >35  Medium  Female   Single  Yes
10    <21  Medium  Female  Married  Yes
11  21-35  Medium    Male  Married  Yes
12  21-35    High  Female   Single  Yes
13    >35  Medium    Male  Married   No

In [9]:
df.describe()

Age  Income Gender      Ms Buys
count    14      14     14      14   14
unique    3       3      2       2    2
top     <21  Medium   Male  Single  Yes
freq      5       6      7       7    9

In [12]:
df.dtypes

Age       object
Income    object
Gender    object
Ms        object
Buys      object
dtype: object

In [14]:
df['Buys'].value_counts()

Yes    9
No     5
Name: Buys, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()



Age:  [('<21',), ('<21',), ('21-35',), ('>35',), ('>35',), ('>35',), ('21-35',), ('<21',), ('<21',), ('>35',), ('<21',), ('21-35',), ('21-35',), ('>35',)]
Income:  [('High',), ('High',), ('High',), ('Medium',), ('Low',), ('Low',), ('Low',), ('Medium',), ('Low',), ('Medium',), ('Medium',), ('Medium',), ('High',), ('Medium',)]
Gender:  [('Male',), ('Male',), ('Male',), ('Male',), ('Female',), ('Female',), ('Female',), ('Male',), ('Female',), ('Female',), ('Female',), ('Male',), ('Female',), ('Male',)]
Ms:  [('Single',), ('Married',), ('Single',), ('Single',), ('Single',), ('Married',), ('Married',), ('Single',), ('Married',), ('Single',), ('Married',), ('Married',), ('Single',), ('Married',)]


In [16]:
x = df.iloc[:,:-1]
x=x.apply(le.fit_transform)

In [17]:
y = df.iloc[:, -1]

In [26]:
print('Age: ', list(zip(df.iloc[:,0], x.iloc[:, 0])))
print('Income: ', list(zip(df.iloc[:,1], x.iloc[:, 1])))
print('Gender: ', list(zip(df.iloc[:,2], x.iloc[:, 2])))
print('Ms: ', list(zip(df.iloc[:,3], x.iloc[:, 3])))

Age:  [('<21', 1), ('<21', 1), ('21-35', 0), ('>35', 2), ('>35', 2), ('>35', 2), ('21-35', 0), ('<21', 1), ('<21', 1), ('>35', 2), ('<21', 1), ('21-35', 0), ('21-35', 0), ('>35', 2)]
Income:  [('High', 0), ('High', 0), ('High', 0), ('Medium', 2), ('Low', 1), ('Low', 1), ('Low', 1), ('Medium', 2), ('Low', 1), ('Medium', 2), ('Medium', 2), ('Medium', 2), ('High', 0), ('Medium', 2)]
Gender:  [('Male', 1), ('Male', 1), ('Male', 1), ('Male', 1), ('Female', 0), ('Female', 0), ('Female', 0), ('Male', 1), ('Female', 0), ('Female', 0), ('Female', 0), ('Male', 1), ('Female', 0), ('Male', 1)]
Ms:  [('Single', 1), ('Married', 0), ('Single', 1), ('Single', 1), ('Single', 1), ('Married', 0), ('Married', 0), ('Single', 1), ('Married', 0), ('Single', 1), ('Married', 0), ('Married', 0), ('Single', 1), ('Married', 0)]


In [18]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [19]:
test_x = np.array([1,1,0,0])
pred_y = classifier.predict([test_x])
print(test_x, pred_y[0])

[1 1 0 0] Yes


C:\Python 3.9.7\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [27]:
test_x=np.array([2,2,0,0])
pred_y=classifier.predict([test_x])
print("Predicted class for input [Age > 35, Income = Medium,Gender = Female, Marital Status = Married]\n", test_x," is ",pred_y[0])

Predicted class for input [Age > 35, Income = Medium,Gender = Female, Marital Status = Married]
 [2 2 0 0]  is  No


C:\Python 3.9.7\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('./Lipstick.csv')

In [3]:
df

Id    Age  Income  Gender       Ms Buys
0    1    <21    High    Male   Single   No
1    2    <21    High    Male  Married   No
2    3  21-35    High    Male   Single  Yes
3    4    >35  Medium    Male   Single  Yes
4    5    >35     Low  Female   Single  Yes
5    6    >35     Low  Female  Married   No
6    7  21-35     Low  Female  Married  Yes
7    8    <21  Medium    Male   Single   No
8    9    <21     Low  Female  Married  Yes
9   10    >35  Medium  Female   Single  Yes
10  11    <21  Medium  Female  Married  Yes
11  12  21-35  Medium    Male  Married  Yes
12  13  21-35    High  Female   Single  Yes
13  14    >35  Medium    Male  Married   No

In [5]:
df.drop(['Id'], inplace=True, axis=1)

In [6]:
df

Age  Income  Gender       Ms Buys
0     <21    High    Male   Single   No
1     <21    High    Male  Married   No
2   21-35    High    Male   Single  Yes
3     >35  Medium    Male   Single  Yes
4     >35     Low  Female   Single  Yes
5     >35     Low  Female  Married   No
6   21-35     Low  Female  Married  Yes
7     <21  Medium    Male   Single   No
8     <21     Low  Female  Married  Yes
9     >35  Medium  Female   Single  Yes
10    <21  Medium  Female  Married  Yes
11  21-35  Medium    Male  Married  Yes
12  21-35    High  Female   Single  Yes
13    >35  Medium    Male  Married   No

In [7]:
df.describe()

Age  Income Gender      Ms Buys
count    14      14     14      14   14
unique    3       3      2       2    2
top     <21  Medium   Male  Single  Yes
freq      5       6      7       7    9

In [9]:
df['Buys'].value_counts()

Yes    9
No     5
Name: Buys, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
x = df.iloc[:, :-1]
x =x.apply(le.fit_transform)

In [13]:
y = df.iloc[:, -1]

In [14]:
print('Age: ', list(zip(df.iloc[:, 0], x.iloc[:, 0])))
print('Income: ', list(zip(df.iloc[:, 1], x.iloc[:, 1])))
print('Gender: ', list(zip(df.iloc[:, 2], x.iloc[:, 2])))
print('Ms: ', list(zip(df.iloc[:, 3], x.iloc[:, 3])))

Age:  [('<21', 1), ('<21', 1), ('21-35', 0), ('>35', 2), ('>35', 2), ('>35', 2), ('21-35', 0), ('<21', 1), ('<21', 1), ('>35', 2), ('<21', 1), ('21-35', 0), ('21-35', 0), ('>35', 2)]
Income:  [('High', 0), ('High', 0), ('High', 0), ('Medium', 2), ('Low', 1), ('Low', 1), ('Low', 1), ('Medium', 2), ('Low', 1), ('Medium', 2), ('Medium', 2), ('Medium', 2), ('High', 0), ('Medium', 2)]
Gender:  [('Male', 1), ('Male', 1), ('Male', 1), ('Male', 1), ('Female', 0), ('Female', 0), ('Female', 0), ('Male', 1), ('Female', 0), ('Female', 0), ('Female', 0), ('Male', 1), ('Female', 0), ('Male', 1)]
Ms:  [('Single', 1), ('Married', 0), ('Single', 1), ('Single', 1), ('Single', 1), ('Married', 0), ('Married', 0), ('Single', 1), ('Married', 0), ('Single', 1), ('Married', 0), ('Married', 0), ('Single', 1), ('Married', 0)]


In [15]:
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [16]:
test_x = np.array([2,2,0,0])
pre_y = classifier.predict([test_x])
print(test_x, pre_y)

[2 2 0 0] ['No']


C:\Python 3.9.7\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
